return PlaceObj('ModDef', {
	'title', "Buy More Prefabs",
	'description', "Generates missing cargo definitions for any building that is flagged as requiring a prefab that does not already have one.\n\nWeight is the total weight of all ingredients, and price is total price of all ingredients plus 20%.",
	'last_changes', "Initial version",
	'id', "nOb3J2k",
	'pops_desktop_uuid', "16246452-f436-4788-b0fe-2e4d0e5dc8d8",
	'pops_any_uuid', "d86f00a4-3c6a-4b94-a5a8-d08eafd950ff",
	'author', "mrudat",
	'version', 3,
	'lua_revision', 233360,
	'saved_with_revision', 245618,
	'code', {
		"Code/Script.lua",
	},
	'has_options', true,
	'saved', 1563162367,
	'TagGameplay', true,
	'TagBuildings', true,
	'TagTools', true,
})